### PR TITLE
Feature/change openstack lib

### PR DESCRIPTION
**Pull request by tdutrion**

### CODE REVIEW

**Comment by JeroenVanOort** [comment]
Is there anything I could help with to keep this moving? Through a Laravel package, we use this package in many projects at our company and we'd love to help out where needed.

**Comment by tdutrion** [comment]
There's a lot of work to do on this PR I would say. Somehow I changed non-related stuff (code style... how is this related...).
Other than that I am absolutely not sure where I left off. I'm not using it at the moment on work projects so if you want to take over go ahead. Not sure whether it's best creating an new PR altogether 😄

**Comment by alcalyn** [comment]
This PR is useful, at least for the composer.json and library upgrades, which are now required to make it work on a project with up-to-date dependencies.

I don't know what I can do more to have this merged, but I can say it works on a symfony 5 project hosted on OVH Cloud, with "basic" needs like read/upload files on a object storage.

I also had to open this PR https://github.com/php-opencloud/openstack/pull/331 first

**Comment by alcalyn** [comment]
``` php
    public function writeStream($path, $resource, Config $config)
    {
        return $this->write($path, $resource, $config);
    }
```

This seems no longer works, `The key provided "content" has the wrong value type. You provided Resource id #X (resource) but was expecting string`.

This patch make file writing works: https://github.com/tdutrion/flysystem-rackspace/pull/1

**Comment by alcalyn** [comment]
Here is the patch to make php-cs-fixer green: https://github.com/tdutrion/flysystem-rackspace/pull/2

**Pull request closed without merging**
